apiVersion: v1
kind: Service
metadata:
  name: core
  namespace: rota
spec:
  type: ClusterIP
  selector:
    app: core
  ports:
    - name: proxy
      port: 8000
      targetPort: 8000
    - name: api
      port: 8001
      targetPort: 8001
