apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: rota
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      imagePullSecrets:
        - name: dockerhub-palverdata
      containers:
        - name: dashboard
          image: palverdata/rota_front:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
          envFrom:
            - configMapRef:
                name: rota-config
            - secretRef:
                name: rota-secrets
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: front
  namespace: rota
  labels:
    app: front
spec:
  type: LoadBalancer
  selector:
    app: front
  ports:
    - name: http
      port: 3000
      targetPort: 3000
